"""usuarios ativo

Revision ID: 1168dcb560eb
Revises: 75ac0e9368d8
Create Date: 2026-09-14 18:46:03.868623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1168dcb560eb'
down_revision: Union[str, Sequence[str], None] = '75ac0e9368d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('ativa', sa.Boolean(), nullable=False))
    op.drop_column('categorias', 'ativo')
    op.add_column('usuarios', sa.Column('ativo', sa.Boolean(), nullable=False))
    op.drop_column('usuarios', 'ativa')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ativa', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('usuarios', 'ativo')
    op.add_column('categorias', sa.Column('ativo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('categorias', 'ativa')
    # ### end Alembic commands ###
